import { Category } from "@/types";

export const BRAND = {
  name: "News Junction",
  taglineHi: "सच्ची खबर, हर नजर",
  taglineEn: "REAL NEWS, REAL IMPACT",
  navy: "#1a2b4c",
  red: "#c41e20",
};

export const DEFAULT_CATEGORIES: Category[] = [
  { id: "home", nameHi: "होम", nameEn: "Home", slug: "home", isActive: true, order: 0 },
  { id: "desh", nameHi: "देश", nameEn: "India", slug: "desh", isActive: true, order: 1 },
  { id: "rajya", nameHi: "राज्य", nameEn: "State", slug: "rajya", isActive: true, order: 2 },
  { id: "duniya", nameHi: "दुनिया", nameEn: "World", slug: "duniya", isActive: true, order: 3 },
  { id: "khel", nameHi: "खेल", nameEn: "Sports", slug: "khel", isActive: true, order: 4 },
  { id: "manoranjan", nameHi: "मनोरंजन", nameEn: "Entertainment", slug: "manoranjan", isActive: true, order: 5 },
  { id: "technology", nameHi: "टेक्नोलॉजी", nameEn: "Technology", slug: "technology", isActive: true, order: 6 },
  { id: "vyapar", nameHi: "व्यापार", nameEn: "Business", slug: "vyapar", isActive: true, order: 7 },
  { id: "swasthya", nameHi: "स्वास्थ्य", nameEn: "Health", slug: "swasthya", isActive: true, order: 8 },
  { id: "video", nameHi: "वीडियो", nameEn: "Videos", slug: "video", isActive: true, order: 9 },
];

export const TRANSLATIONS = {
  hi: {
    breakingNews: "ब्रेकिंग न्यूज़",
    trendingNews: "ट्रेंडिंग न्यूज़",
    latestNews: "लेटेस्ट न्यूज़",
    popularNews: "लोकप्रिय खबरें",
    viewMore: "और देखें",
    search: "खोजें",
    searchPlaceholder: "खबरें खोजें...",
    home: "होम",
    relatedNews: "संबंधित खबरें",
    share: "शेयर करें",
    publishedOn: "प्रकाशित",
    by: "द्वारा",
    all: "सब",
    news: "खबरें",
    videos: "वीडियो",
    photos: "फोटो",
    noResults: "कोई परिणाम नहीं मिला",
    readMore: "और पढ़ें",
    shortContent: "संक्षिप्त",
    fullStory: "पूरी खबर",
    readFullStory: "पूरी खबर पढ़ें",
    showLess: "कम दिखाएं",
    selectLanguage: "भाषा चुनें",
    set: "सेट करें",
    loading: "लोड हो रहा है...",
    minutesAgo: "मिनट पहले",
    hoursAgo: "घंटे पहले",
    daysAgo: "दिन पहले",
  },
  en: {
    breakingNews: "Breaking News",
    trendingNews: "Trending News",
    latestNews: "Latest News",
    popularNews: "Popular News",
    viewMore: "View More",
    search: "Search",
    searchPlaceholder: "Search news...",
    home: "Home",
    relatedNews: "Related News",
    share: "Share",
    publishedOn: "Published",
    by: "By",
    all: "All",
    news: "News",
    videos: "Videos",
    photos: "Photos",
    noResults: "No results found",
    readMore: "Read More",
    shortContent: "Short",
    fullStory: "Full Story",
    readFullStory: "Read Full Story",
    showLess: "Show less",
    selectLanguage: "Select Language",
    set: "Set",
    loading: "Loading...",
    minutesAgo: "minutes ago",
    hoursAgo: "hours ago",
    daysAgo: "days ago",
  },
} as const;
